sudo: required
dist: trusty

language: cpp
compiler:
  - gcc

script:
  - export CC=gcc-5
  - export CXX=g++-5
  - cd test
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./test_libchen

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - gcc-5
      - g++-5

notifications:
  email:
    on_success: never
    on_failure: always