language: cpp

matrix:
  include:
#    - os: linux
#      env: Linux
#      dist: trusty
#      script:
#        - mkdir build
#        - cd build
#        - cmake -DCHEN_CODE_COVERAGE=ON ..
#        - make
#        - test/libchen-test
#        - bash <(curl -s https://codecov.io/bash)

    - os: linux
      env: Android
      dist: trusty
      before_install:
        - rm -rf $HOME/android-ndk-r16b
        - curl -L http://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip -O
        - unzip -oq android-ndk-r16b-linux-x86_64.zip
        - rm android-ndk-r16b-linux-x86_64.zip
        - export NDK_ROOT=$HOME/android-ndk-r16b
      script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_SYSTEM_NAME=Android -DCMAKE_ANDROID_NDK=$NDK_ROOT -DCMAKE_SYSTEM_VERSION=17 -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a -DCMAKE_ANDROID_STL_TYPE=gnustl_static ..
        - make
        - test/libchen-test

#    - os: osx
#      env: macOS
#      osx_image: xcode9.2
#      script:
#        - mkdir build
#        - cd build
#        - cmake -G Xcode ..
#        - xcodebuild -target libchen-test -project libchen.xcodeproj -configuration Release
#        - test/Release/libchen-test