language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: osx
      compiler: clang

script:
  - cd test
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./test_libchen --data=../data