language: cpp

matrix:
  include:
    - os: linux
      env: Linux
      dist: trusty
      script:
        - mkdir build
        - cd build
        - cmake -DCHEN_CODE_COVERAGE=ON ..
        - make
        - test/libchen-test --data=../test/data
        - bash <(curl -s https://codecov.io/bash)

    - os: osx
      env: macOS
      osx_image: xcode9.2
      script:
        - mkdir build
        - cd build
        - cmake -G Xcode ..
        - xcodebuild -target libchen-test -project libchen.xcodeproj -configuration Release
        - test/Release/libchen-test --data=../test/data