sudo: required
dist: trusty

language: cpp
compiler:
  - clang

#script:
#  - mkdir build
#  - cd build
#  - cmake ..
#  - make

script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5