sudo: required
dist: trusty

language: cpp
compiler:
  - gcc

script:
  - cd test
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./test_libchen --data=../data

notifications:
  email:
    on_success: never
    on_failure: always