os: Visual Studio 2015

platform:
  - x64

environment:
  matrix:
    - config: Debug
    - config: Release

matrix:
  fast_finish: true

shallow_clone: true

clone_folder: c:\projects\libchen

before_build:
  - pwd
  - cmake --version
  - cd test
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" ..
  - ls

build:
  project: C:\projects\libchen\test\build\test_libchen.sln

test_script:
  - pwd
  - echo %config%
  - .\%config%\test_libchen.exe