os: Visual Studio 2015

platform:
  - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

shallow_clone: true

clone_folder: c:\projects\libchen

before_build:
  - pwd
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..

build:
  project: C:\projects\libchen\build\test_libchen.sln

test_script:
  - cmd: pwd
  - cmd: ls